# Generated by Django 3.1.3 on 2021-07-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
