# Generated by Django 3.1.3 on 2021-07-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.URLField(null=True),
        ),
    ]
