# Generated by Django 3.1.3 on 2021-07-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Project',
        ),
    ]
