# Generated by Django 3.1.3 on 2021-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_album_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.ImageField(default='..media/makingmovies.jpg', null=True, upload_to='../media/'),
        ),
    ]
