# Generated by Django 3.1.3 on 2021-07-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
