# Generated by Django 3.1.3 on 2021-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tracklist',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
