# Generated by Django 3.1.3 on 2021-07-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210706_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='accentcolour',
            field=models.CharField(default=(0, 0, 0), max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='primcolour',
            field=models.CharField(default=(0, 0, 0), max_length=14),
            preserve_default=False,
        ),
    ]
