# Generated by Django 3.1.3 on 2021-07-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210707_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.ImageField(default='makingmovies.jpg', null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='imgThumb',
            field=models.ImageField(default='makingmovies.jpg', null=True, upload_to='upload/'),
        ),
    ]
