# Generated by Django 3.1.3 on 2021-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210707_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='accentcolourB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='accentcolourG',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='accentcolourR',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='primcolourB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='primcolourG',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='primcolourR',
            field=models.IntegerField(),
        ),
    ]
