# Generated by Django 3.1.3 on 2021-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210707_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='imgThumb',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
