# Generated by Django 3.1.3 on 2021-07-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210707_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imgThumb',
        ),
    ]
