# Generated by Django 3.1.3 on 2021-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_album_imgthumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
