# Generated by Django 3.1.3 on 2021-07-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210708_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isdone',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='todo',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
